---
collections:
  - name: azure.azcollection
    version: "=3.6.0"
  - name: cisco.ise
    version: ">=2.5.0"
  - name: ansible.netcommon
    version: "=7.2.0"
  - name: community.crypto
    version: ">=2.0.0"
  - name: ansible.posix
    version: ">=1.0.0"