---
plugin: azure.azcollection.azure_rm
include_vm_resource_groups:
  - "{{ lookup('env', 'AZURE_RESOURCE_GROUP', default='rg-iseble-azure') }}"
auth_source: env
keyed_groups:
  - prefix: tag
    key: tags
  - prefix: location
    key: location
  - prefix: vm_size
    key: hardware_profile.vm_size
  - prefix: os_type
    key: os_profile.linux_configuration
    separator: ""
  - prefix: private_ip
    key: private_ipv4_addresses
    separator: ""
  - prefix: public_ip
    key: public_ipv4_addresses
    separator: ""
hostvar_expressions:
  ansible_host: public_ipv4_addresses[0] || private_ipv4_addresses[0]
  ansible_user: "{{ lookup('env', 'ISE_ADMIN_USER', default='iseadmin') }}"
  ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PRIVATE_KEY_FILE', default='files/ssh_keys/iseble-azure') }}"
  ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' 